import { makeStyles } from "@mui/styles";

const useStyles = makeStyles({
  wrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    flexDirection: "column",
    position: "relative",
    "@media (max-width:1000px)": {
      height: "100%",
      padding: 0,
      width: "100% !important",
      marginBottom: 30,
    },
  },
  cardsWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    flexDirection: "row",
    gap: 100,
    "@media (max-width:1000px)": {
      flexDirection: "column",
      gap: 50,
      width: "100%",
    },
  },
  cardWrapper: {
    zIndex: 4,
    width: 450,
    height: "100%",
    borderRadius: 16,
    background:
      "var(--1, linear-gradient(154deg, #482B19 0.88%, #664532 98.45%))",
    boxShadow: "5px 7px 39px 0px rgba(0, 0, 0, 0.51)",
    "@media (max-width:1000px)": {
      width: "100%",
    },
  },
  cardWrapper1: {
    zIndex: 4,
    width: 450,
    height: "100%",
    borderRadius: 16,
    background: "var(--2, linear-gradient(155deg, #1E150F 0%, #292623 100%))",
    boxShadow: "5px 7px 39px 0px rgba(0, 0, 0, 0.51)",
    "@media (max-width:1000px)": {
      width: "100%",
    },
  },
  card: {
    position: "relative",
    margin: 20,
    borderRadius: 16,
    border: "2px solid #FFF",
    height: 728,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "30px 20px",
    "@media (max-width:1000px)": {
      margin: 5,
      padding: "30px 20px 20px 20px",
      height: "100%",
    },
  },

  cardTitle: {
    color: "#FFF",
    fontSize: 30,
    textTransform: "uppercase",
    fontWeight: 700,
  },
  cardList: {
    color: "#FFF",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    padding: 0,
    gap: 10,
    marginBottom: 30,
    "@media (max-width:1000px)": {
      marginBottom: 30,
      gap: 15,
    },
    "&>li": {
      fontSize: 16,
      textDecoration: "none",
      display: "flex",
      alignItems: "center",
      flexDirection: "column",
      textAlign: "center",
      fontWeight: 300,
      fontFamily: `"Exo 2", sans-serif !important`,
    },
  },
  cardListItemLined: {
    textDecorationLine: "line-through",
    color: "rgba(255, 255, 255, 0.60)",
  },
  originalPrice: {
    fontSize: 16,
    color: "#FFF",
    marginBottom: "-10px",
    textDecorationLine: "line-through",
    "@media (max-width:1000px)": {
      color: "rgba(255, 255, 255, 0.60)",
    },
  },
  discountedPrice: { fontSize: 40, color: "#FFF", fontWeight: 700 },
  priceDescription: {
    fontSize: 12,
    color: "#FFF",
    marginTop: "-7px",
  },
  button: {
    position: "relative",
    background:
      "var(--BTN_MAIN, radial-gradient(29.03% 41.72% at 50% 99.35%, #EDC9AF 0.02%, #CCA081 47.92%, #BA7441 100%))",
    padding: "19px 25px 18px 25px",
    borderRadius: 15,
    border: "none",
    color: "#FFF",
    borderBottom: "5px solid #482B19",
    width: 250,
    zIndex: 1000,
    textTransform: "uppercase",
    fontWeight: 600,
    fontSize: 18,
    marginTop: 20,
    "&:hover": {
      marginTop: 22,
      cursor: "pointer",
      borderBottom: "none",
      filter: "drop-shadow(0px 0px 40px #B7703D)",
      transition: "all 0.3s ease",
      background:
        "radial-gradient(69.13% 99.35% at 50% 99.35%, #EDC9AF 0.02%, #CCA081 47.92%, #BA7441 100%)",
    },
    boxShadow: "0 0 25.5px rgba(183, 112, 61, 0.11)",
    "@media (max-width:1000px)": {
      marginBottom: 0,
    },
  },
  blackButton: {
    background: "#FFF",
    color: "#000",
    borderBottom: "5px solid #5F5F5F",
    position: "relative",
    padding: "19px 25px 18px 25px",
    borderRadius: 15,
    border: "none",
    width: 250,
    zIndex: 1000,
    textTransform: "uppercase",
    fontWeight: 600,
    fontSize: 18,
    marginTop: 20,
    "&:hover": {
      marginTop: 22,
      cursor: "pointer",
      borderBottom: "none",
      filter: "drop-shadow(0px 0px 40px #FFF)",
      transition: "all 0.3s ease",
      background: "#DADADA",
    },
    boxShadow: "0 0 25.5px rgba(183, 112, 61, 0.11)",
    "@media (max-width:1000px)": {
      marginBottom: 0,
    },
  },
  label: {
    transform: "rotate(6deg)",
    position: "absolute",
    top: "-35px",
    right: "-30px",
    color: "#FFF",
    backgroundColor: "#B7703D",
    borderRadius: 12,
    padding: "12px 20px",
    textTransform: "uppercase",
    fontWeight: 600,
    fontSize: 14,
    fontFamily: `"Exo 2", sans-serif !important`,
    "&>div": {
      marginTop: "-5px",
      fontSize: 25,
    },
    "@media (max-width:1000px)": {
      top: "-20px",
      right: "-10px",
      marginRight: "-5px",
    },
  },
  blockName: {
    position: "relative",
    color: "#482B19",
    fontSize: 34,
    fontWeight: 600,
    textTransform: "uppercase",
    textAlign: "center",
    zIndex: 4,
    marginBottom: 50,
    "@media (max-width:1000px)": {
      marginBottom: 30,
    },
  },
  priceBlock: {
    position: "absolute",
    bottom: 50,
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    textAlign: "center",
  },
  bonus: {
    marginTop: "-50px",
    marginBottom: "-25px",
    marginLeft: "-40px",
    width: 150,
    "@media (max-width:1000px)": {
      marginTop: "-50px",
    },
  },
  bonusBlock: {
    display: "flex",
  },
});

export default useStyles;
