import { makeStyles } from "@mui/styles";

const useStyles = makeStyles({
  wrapper: {
    position: "relative",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingBottom: 50,
    "@media (max-width:1000px)": {
      padding: "0px 20px",
    },
  },
  label: {
    zIndex: 5,
    color: "#FFF",
    fontSize: 35,
    fontFamily: "Playfair Display",
    textTransform: "uppercase",
    fontWeight: 800,
    textShadow: "0px 0px 100px #A66B4D, 2px 3px 3px #000",
    marginBottom: 50,
    "@media (max-width:1000px)": {
      textAlign: "center",
      zIndex: 6,
      fontSize: 50,
    },
  },
  ratesWrapper: {
    display: "flex",
    zIndex: 5,
    gap: 100,
    "@media (max-width:1000px)": {
      flexDirection: "column",
    },
  },
  rate: {
    position: "relative",
    width: 300,
    borderRadius: 30,
    zIndex: 5,
    border: "1px solid #FFF",
    background: "#221207",
    boxShadow: "8px 8px 5.6px 0px rgba(0, 0, 0, 0.43)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: 25,
    height: "100%",
  },

  rateImg: {
    width: 150,
    marginTop: "-50px",
  },
  rateName: {
    color: "#FFF",
    textAlign: "center",
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 30,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  available: {
    color: "#FFF",
    textAlign: "center",
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 16,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  rateBlock: {
    borderRadius: 30,
    border: "2px solid #FFF",
    boxShadow: "8px 8px 5.6px 0px rgba(0, 0, 0, 0.43)",
    padding: "9px 30px",
    textTransform: "uppercase",
    color: "#FFF",
    margin: "15px 0px",
    fontWeight: 700,
  },
  blockContains: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    "&>div": {
      color: "#FFF",
      textAlign: "center",
      fontFamily: `"Exo 2", sans-serif !important`,
      fontSize: 12,
      fontWeight: 600,
    },
  },
  rateBonus: {
    borderRadius: 30,
    border: "2px solid #B7703D",
    boxShadow: "8px 8px 5.6px 0px rgba(0, 0, 0, 0.43)",
    padding: "9px 30px",
    textTransform: "uppercase",
    color: "#B7703D",
    margin: "15px 0px",
    fontWeight: 700,
  },
  disabledFeatures: {
    color: "rgba(255, 255, 255, 0.40) !important",
    textDecoration: "line-through",
  },
  blockBonuses: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    "&>div": {
      color: "#B7703D",
      textAlign: "center",
      fontFamily: `"Exo 2", sans-serif !important`,
      fontSize: 12,
      fontWeight: 600,
    },
  },
  actualPrice: {
    marginTop: 30,
    borderRadius: 14,
    border: "1px solid #FFF",
    background: "#B7703D",
    padding: "10px 40px",
    color: "#FFF",
    textAlign: "center",
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 16,
    fontWeight: 500,
    letterSpacing: 0.32,
    textTransform: "uppercase",
  },
  price: {
    marginTop: "-10px",
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 50,
    fontWeight: 700,
  },
  fullPriceLabel: {
    color: "#FFF",
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 16,
    fontWeight: 500,
  },
  fullPrice: {
    marginTop: "-7px",
    color: "#B7703D",
    fontFamily: `"Exo 2", sans-serif !important`,
    fontWeight: 700,
    fontSize: 40,
    textDecoration: "line-through",
  },
  rateButton: {
    position: "absolute",
    bottom: 120,
    background: "#FFF",
    padding: "15px 40px 15px 40px",
    borderRadius: 7,
    border: "none",
    color: "#221207",
    borderBottom: "5px solid #C2C2C2",
    zIndex: 1000,
    textTransform: "uppercase",
    fontWeight: 700,
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 25,
    marginTop: 20,
    boxShadow: "0 0 25.5px rgba(183, 112, 61, 0.11)",
    width: 237,
    "&:hover": {
      marginTop: 22,
      cursor: "pointer",
      borderBottom: "none",
      filter: "drop-shadow(0px 0px 40px #FFF)",
      transition: "all 0.3s ease",
      background: "#FFF",
    },
    "&:disabled": {
      color: "#482B19",
      border: "2px solid  #482B19",
      boxShadow: "none",
      transform: "rotate(-2.309deg);",
      background: "transparent",
      "&:hover": {
        marginTop: 20,
        cursor: "auto",
        filter: "none",
        background: "transparent",
      },
    },

    "@media (max-width:1000px)": {
      marginBottom: 0,
    },
  },
  rateButton2: {
    position: "absolute",
    bottom: 40,
    background: "#EFAA78",
    padding: "16px 10px 15px 10px",
    borderRadius: 7,
    border: "none",
    color: "#221207",
    borderBottom: "5px solid #78553C",
    zIndex: 1000,
    textTransform: "uppercase",
    fontWeight: 700,
    fontFamily: `"Exo 2", sans-serif !important`,
    fontSize: 20,
    marginTop: 20,
    width: 237,
    boxShadow: "0 0 25.5px rgba(183, 112, 61, 0.11)",
    "&:hover": {
      marginTop: 22,
      cursor: "pointer",
      borderBottom: "none",
      filter: "drop-shadow(0px 0px 40px #B7703D)",
      transition: "all 0.3s ease",
    },
    "&:disabled": {
      color: "#482B19",
      border: "2px solid  #482B19",
      boxShadow: "none",
      transform: "rotate(-2.309deg);",
      background: "transparent",
      "&:hover": {
        marginTop: 20,
        cursor: "auto",
        filter: "none",
        background: "transparent",
      },
    },

    "@media (max-width:1000px)": {
      marginBottom: 0,
    },
  },
  figure: {
    position: "absolute",
    right: 0,
    width: 600,
    top: "-200px",
    "@media (max-width:1000px)": {
      display: "none",
    },
  },
  figure2: {
    position: "absolute",
    left: "-300px",
    bottom: 300,
    width: 600,
    transform: "scale(-1, -1)",
    "@media (max-width:1000px)": {
      display: "none",
    },
  },
  ratesLight: {
    position: "absolute",
    "@media (max-width:1000px)": {
      display: "none",
    },
  },
  ratesEllipse: {
    position: "absolute",
    right: 0,
    bottom: 0,
    "@media (max-width:1000px)": {
      display: "none",
    },
  },
  pen1: {
    position: "absolute",
    left: 0,
    bottom: 0,
    transform: "scale(-1, -1)",
    width: 180,
    "@media (max-width:1000px)": {
      display: "none",
    },
  },
  link: {
    color: "#FFF",
    fontSize: 12,
  },
  price1: {
    marginTop: 10,
    color: "#FFF",
    marginBottom: 180,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 16,
    gap: 10,
  },
});

export default useStyles;
